name: Zip chatbot

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Archive chatbot
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: chatbot.zip
          directory: chatbot

      - name: Upload chatbot
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: chatbot/chatbot.zip
          asset_name: chatbot.zip
          overwrite: true
          body: joomla-plugin
